<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ActiveMQ/ActiveMQRecDemo/jmsin" name="jmsin-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="jmsin.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ActiveMQ/ActiveMQRecDemo/jmsin"/>
    <wsdl:binding name="Consume_Message_ptt-binding" type="jms:Consume_Message_ptt" xmlns:jms="http://xmlns.oracle.com/pcbpel/adapter/jms/ActiveMQ/ActiveMQRecDemo/jmsin">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Consume_Message">
            <soap:operation soapAction="Consume_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>